apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres
  name: postgres
  namespace: job-processing
spec:
  ports:
  - name: "5432"
    port: 5432
  selector:
    app: postgres
  clusterIP: None
status:
  loadBalancer: {}
