apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: job-processing
spec:
  selector:
    matchLabels:
      app: postgres 
  serviceName: "postgres"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: postgres # has to match .spec.selector.matchLabels
    spec:
      volumes: 
      - name: db-init
        configMap: 
         name: db-init 
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:15.4-alpine
        env:
         - name: POSTGRES_DB
           value: jobqueue
         - name: POSTGRES_USER
           value: jobuser
         - name: POSTGRES_PASSWORD
           value: jobpass123
        ports:
        - containerPort: 5432
          name: postgress
        volumeMounts:
        - name: db-init
          mountPath: /docker-entrypoint-initdb.d
        - name: postgress-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgress-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi